name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: formatting
        uses: "lgeiger/lack_action@master"
        with:
          args: .
      - uses: psf/black@stable
